desafio_01 @mschonfinkel
training-center/elixir-study-group pull request #13
Opened 2018-03-18 20:22 UTC by mschonfinkel

Solução do primeiro desafio

2018-03-19 13:56 UTC, gionaufal commented
A implementação está bem legal! Só o teste que acho que ficou sobrando do `mix new`, porque ainda está com o método `hello` que não existe mais :)

2018-03-19 14:41 UTC, rafaels88 requested changes

2018-03-19 14:41 UTC, rafaels88 commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    case userInput IO.gets dica do
[Minor] Como convenção nos códigos em Elixir, eu alteraria este método `userInput`(camelCase) para `user_input` (snake_case).

2018-03-19 14:41 UTC, rafaels88 commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    case userInput IO.gets dica do
Também, talvez você pudesse deixar um pouco mais explicito a intenção desta função `userInput`. Lendo parece que ela é o próprio valor, uma variável, mas na verdade ela é uma função para normalizar o valor dos inputs. Que tal alterar o nome dela pra algo como, "normalize_input"?

2018-03-19 14:41 UTC, rafaels88 commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    case userInput IO.gets dica do
Uma última coisa, você omitiu o parênteses completamente nessa linha, e isso geralmente é algo que se evita. No máximo a gente omite de uma chamada, não de tudo, senão fica difícil de ler e pode gerar `warnings` na hora de compilar.

Mas ainda pensando na forma funcional de se programar, você poderia utilizar um pipeline operator aqui. Eu alteraria pra algo como (aproveitando os feedback que deixei acima),

`case IO.gets(dica) |> normalize_input do`

O que acha?

2018-03-19 14:41 UTC, rafaels88 commented on solucoes/desafio_01/mschonfinkel/test/mschonfinkel_test.exs
> +defmodule MschonfinkelTest do
Este teste você pode deletar, já que está incorreto, inclusive :)

2018-03-19 15:49 UTC, mschonfinkel commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    case userInput IO.gets dica do
@rafaels88 Ainda estou tentando entender o mix e como testes funcionam no elixir! Vou refatorar! :+1:

2018-03-19 15:50 UTC, mschonfinkel commented on solucoes/desafio_01/mschonfinkel/test/mschonfinkel_test.exs
> +defmodule MschonfinkelTest do
@rafaels88  Ainda estou tentando entender o mix e como testes funcionam no elixir! Vou refatorar! Obrigado pelas várias sugestões! :)

2018-03-19 15:52 UTC, mschonfinkel commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    case userInput IO.gets dica do
A absência de parênteses é memória muscular do Haskell XD, vou colocar

2018-03-19 15:53 UTC, mschonfinkel commented
@gionaufal Vou alterar o teste, ainda não entendo bem como o mix e testes funcionam em Elixir.

2018-03-19 15:55 UTC, mschonfinkel commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    case userInput IO.gets dica do
Existe algum Style Guide para Elixir assim como existe o PEP8 pro Python? Estava justamente com dúvida sobre como nomear funções e módulos.

2018-03-19 16:32 UTC, rafaels88 commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    case userInput IO.gets dica do
Olha existe mas não é igual ao PEP8 que é algo oficial. Se você googlar aí vai achar esse por exemplo: https://github.com/christopheradams/elixir_style_guide

Por hora, acho que também podemos usar Elixir >= 1.6 e utilizar `mix credo` (dependencia externa) e `mix format` (built-in) pra formatar e analisar o estilo dos nossos códigos caso você tiver afim. 

No meu caso eu usei apenas o `mix format` mesmo

2018-03-20 11:25 UTC, gionaufal approved these changes
:metal:

2018-03-20 15:11 UTC, lbighetti approved these changes
nice 👍

2018-03-20 15:11 UTC, lbighetti commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    "Dica: " <> Enum.random(@hints) <> "\n"
[minor]: uma alternativa é interpolar o string: 

```elixir
"Dica: #{Enum.random(@hints)}\n"
```

2018-03-20 15:29 UTC, rafaels88 approved these changes

2018-03-20 15:30 UTC, mschonfinkel commented on solucoes/desafio_01/mschonfinkel/lib/mschonfinkel.ex
> +    "Dica: " <> Enum.random(@hints) <> "\n"
Nice! :)

2018-03-21 06:05 UTC, merged